### ISSUE TITLE
Unable to load from 2025.05.31.

### ISSUE THREAD

**Issue by yamamov** [juliarose/Steam-Market-History-Cataloger#37]
When trying to collect information on steam.
TypeError: Cannot read properties of null (reading 'getAttribute')
I get the above error.
Both in Brave browser and MS Edge.
I am using Japanese and using Japanese Yen.
Has the specification on the Steam side

![err](https://github.com/juliarose/Steam-Market-History-Cataloger/assets/8535094/804ed76b-b03a-4f8d-a11f-5bc6776441a0)
 changed?

**Comment by etomarat** [comment]
I also came across this. Is there a solution?I use Brave and Russian rubles on steam

**Comment by juliarose** [comment]
This is due to Steam removing seller info on history results. I'm preparing an update which should be out within the next few days.

**Comment by yamamov** [comment]
Hi!　I can't wait for it to be registered in the Chrome Extensions Store, so I installed it from the ZIP file and used it.
It's working well. Nice job!
You have helped me just as you did with the previous Japanese Yen support. Thank you from the bottom of my heart for all your help.
...By the way, I've been with Steam for so long that I have more old and useless data than I need.
I think it would be useful to have some kind of UI to manage saved data, such as an 'option to truncate data before a specified point in time', but that's another thread.
Thank you for your quick response.

**Comment by juliarose** [comment]
I appreciate it. I'm not planning on implementing new features at this time.

The issue has been resolved and I've published an update in the chrome extensions store (v1.2.0). It takes some time for the review process to go through but shouldn't be longer than a day.

I refactored much of the codebase so I may have introduced a few bugs although I've personally tested everything as working normally. I also updated the extension to manifest V3. V3 relies on service workers rather than background pages which only run when active, consuming less resources which is nice.
