### ISSUE TITLE
"Nothing to display", but i have transactions

### ISSUE THREAD

**Issue by etomarat** [juliarose/Steam-Market-History-Cataloger#38]
Thank you so much for your work on this great extension! I apologize for the trouble, but I'm having some issues updating the list of transactions today. Could you please take a look at the screenshot I've attached and let me know what the problem might be and how we can fix it? Thank you in advance for your help.
![image](https://github.com/user-attachments/assets/974b0e35-608e-4ee1-bace-b7c3653c1b80)

**Comment by juliarose** [comment]
The state could be messed up. I haven't experienced issues with this personally. I'm somewhat interested in testing it a bit more thoroughly since I did change quite a bit recently, but again I haven't experienced issues myself.

When you get the message "Nothing to display." it simply means the extension wasn't able to find any new listings since the last update. If you view the listings within the extension and your market history and they line up, this is the message you'd get when trying to update again. Is there a difference between what listings are stored in the extension and your market history? If you have any other further activity, is it completely unable to to update its listings?

**Comment by etomarat** [comment]
It looks like there might have been a problem on Steam's end. There were also no new entries in my Steam history, but I did receive purchase/sale notifications via email. I believe everything is back to normal now, and I will be able to check again in the evening.

**Comment by etomarat** [comment]
Everything is working well now. Apparently, the problem was on the side of steam. Thanks!

**Comment by juliarose** [comment]
Good to hear! Marking this as closed now.
